import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import HeaderOne from "@/components/headerone";
import Header from "@/components/header";

const myFont = Roboto ({
  subsets :["latin"],
  weight: ["400","700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myFont.className}
      >
        <HeaderOne/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
